Document: ossec-hids
Title: Debian ossec-hids Manual
Author: <insert document author here>
Abstract: This manual describes what ossec-hids is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ossec-hids/ossec-hids.sgml.gz

Format: postscript
Files: /usr/share/doc/ossec-hids/ossec-hids.ps.gz

Format: text
Files: /usr/share/doc/ossec-hids/ossec-hids.text.gz

Format: HTML
Index: /usr/share/doc/ossec-hids/html/index.html
Files: /usr/share/doc/ossec-hids/html/*.html
